### ISSUE TITLE
Updating the dtree db files.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/ua_classifier#3]
It looks like the dtree files should be updated for more recent browsers. However de dtree repository of the weather channel is not updated and http://openddr.org (**open at own risk**) looks hacked.

I see that the apache project has more recent device databases. http://devicemap.apache.org. Should we get it from them in the future?

```
> ua_classifier:browser_classify("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17").
{ok,[{os,<<>>},
     {version,0},
     {browser,<<"WebKit">>},
     {id,<<"safari">>}]}
```

**Comment by mworrell** [comment]
The devicemap XML data is here http://devicemap-vm.apache.org/data/snapshot/

**Comment by yhafri** [comment]
Hey @mworrell 
Would be great if you can update the [openddr.dtree](https://github.com/zotonic/ua_classifier/blob/master/priv/openddr.dtree) (_953kiB_) with the recent version from this `dClass` fork at [devicemap.dtree](https://github.com/openx/dClass/blob/master/dtrees/devicemap.dtree) (_1.1miB_).
Keep up the good work.

**Comment by mworrell** [comment]
@yhafri done, changed the Makefile to source the files from https://github.com/openx/dClass/tree/master/dtrees
